-- 코드를 작성해주세요
WITH RECURSIVE TEMP AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL 
    
    UNION ALL
    
    SELECT 
        C.ID, C.PARENT_ID, P.GENERATION + 1 AS GENERATION 
    FROM ECOLI_DATA AS C
    JOIN TEMP AS P 
    ON C.PARENT_ID = P.ID
),

NO_CHILD AS (
    SELECT ID,GENERATION
    FROM TEMP
    WHERE ID NOT IN (
        SELECT PARENT_ID
        FROM TEMP 
        WHERE PARENT_ID IS NOT NULL
    )
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM NO_CHILD
GROUP BY GENERATION
ORDER BY GENERATION;

