-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_TREE AS TREE
JOIN (
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE RARITY = 'RARE'
) SUB
ON TREE.PARENT_ITEM_ID = SUB.ITEM_ID
JOIN ITEM_INFO
ON TREE.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID DESC;