

WITH YEARLY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR , MAX(SIZE_OF_COLONY) AS MAX_COLONY_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    )
    
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR , (YEARLY.MAX_COLONY_SIZE - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN YEARLY 
ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)= YEARLY.YEAR
ORDER BY YEAR , YEAR_DEV;