-- 코드를 입력하세요
SELECT ICECREAM_INFO.INGREDIENT_TYPE,  SUM(FIRST_HALF.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO
JOIN FIRST_HALF 
ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ;