SELECT 
    FP.CATEGORY, 
    FP.PRICE AS MAX_PRICE, 
    FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
  AND FP.PRICE = (
      SELECT MAX(SUB.PRICE)
      FROM FOOD_PRODUCT SUB
      WHERE SUB.CATEGORY = FP.CATEGORY
  )
GROUP BY FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
ORDER BY MAX_PRICE DESC;
