SELECT 
    CATEGORY, 
    MAX(PRICE) AS MAX_PRICE, 
    SUBSTRING_INDEX(GROUP_CONCAT(PRODUCT_NAME ORDER BY PRICE DESC), ',', 1) AS PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;
